#!/bin/bash
SNAPRAID_DUP_FILE="/media/926fb5ca-b54e-4dfc-828b-4c25ad072265/Ordner_fuer_Dienste/snapraid-dup-txt/snapraid-dup.txt"

snapraid -G -l $SNAPRAID_DUP_FILE dup

sed -i "1iSnapRAID Dup started at $(date)" $SNAPRAID_DUP_FILE
sed -i ';s/dup://g;s/: dup//g' $SNAPRAID_DUP_FILE
echo "SnapRAID Dup finished at $(date)" >> $SNAPRAID_DUP_FILE

echo "SnapRAID dup file created in"
echo "$SNAPRAID_DUP_FILE"
echo

exit 0

sed -i -f /etc/snapraid.sed.replace | awk '{ \
#gsub("berta", "\033[1;33m&\033[0m"); \
#gsub("alma", "\033[1;31m&\033[0m"); \
#gsub("serina", "\033[1;35m&\033[0m"); \
#gsub("highdy", "\033[1;36m&\033[0m"); print }'
