#!/bin/bash
SNAPRAID_DUP_FILE="/media/926fb5ca-b54e-4dfc-828b-4c25ad072265/Ordner_fuer_Dienste/snapraid-dup-txt/snapraid-dup.txt"

sed -f /etc/snapraid.sed.replace $SNAPRAID_DUP_FILE | \
egrep -v -i '(rtf|ini|jpg|arw|jpg|raf|backup|TFTPd-images|tif|.db|xmv|wdd|Ordner_fuer_Dienste/Torrents)' | awk '{ \
gsub("berta", "\033[1;33m&\033[0m"); \
sub("MediaBerta", "\033[1;34m&\033[0m"); \
gsub("alma", "\033[1;31m&\033[0m"); \
gsub("serina", "\033[1;35m&\033[0m"); \
gsub("highdy", "\033[1;36m&\033[0m"); print }'
