#!/bin/bash
SNAPRAID_DUP_FILE="/media/926fb5ca-b54e-4dfc-828b-4c25ad072265/Ordner_fuer_Dienste/snapraid-dup-txt/snapraid-dup.txt"

case "$1" in
	dup)
		f_create_dup
		;;
	show)
		f_show_dup
		;;
	*)
		f_usage
		;;

f_usage() {
	echo "Usage:"
	}


f_create_dup() {
	snapraid -G -l $SNAPRAID_DUP_FILE dup

	sed -i "1iSnapRAID Dup started at $(date)" $SNAPRAID_DUP_FILE
	sed -i ';s/dup://g;s/: dup//g' $SNAPRAID_DUP_FILE
	echo "SnapRAID Dup finished at $(date)" >> $SNAPRAID_DUP_FILE

	echo "SnapRAID dup file created in"
	echo "$SNAPRAID_DUP_FILE"
	echo

	exit 0
}

f_show_dup() {
	# Get file-change date
	DATE_DUP_FILE="$(stat --format=%Y $SNAPRAID_DUP_FILE)"
	DATE_CONTENT_FILE="$(stat --format=%Y /var/snapraid/content)"

	# check, if duplicate file is older than content
	# That means, that a sync was running after creating
	# a duplicate file, so it's to old
	if [ $DATE_DUP_FILE -lt $DATE_CONTENT_FILE ]; then
		echo "Your duplicate file is older than the content file!"
		echo "Please run 'omv-snapraid-create-dup' to create a new one"
		echo
		exit 1
	fi

	sed -f /etc/snapraid.sed.replace $SNAPRAID_DUP_FILE | \
	egrep -v -i '(rtf|ini|jpg|arw|jpg|raf|backup|TFTPd-images|tif|.db|xmv|wdd|Ordner_fuer_Dienste)' | sed 's/:/ = /' | \
	awk 'BEGIN {FS=":"} \
	{if ($2 < 1048576) {printf ("%1s %.1fkB\n",$1,$2/1024)} \
	else {printf ("%1s %.1fMB\n",$1,$2/1024/1024)}}' | \
	awk '{ \
	gsub("berta", "\033[1;33m&\033[0m"); \
	gsub("MediaBerta", "\033[1;34m&\033[0m"); \
	gsub("alma", "\033[1;31m&\033[0m"); \
	gsub("serina", "\033[1;35m&\033[0m"); \
	gsub("highdy", "\033[1;36m&\033[0m"); print }'
}






