#!/bin/bash
SNAPRAID_DUP_FILE="/media/926fb5ca-b54e-4dfc-828b-4c25ad072265/Ordner_fuer_Dienste/snapraid-dup-txt/snapraid-dup.txt"

snapraid -G -l $SNAPRAID_DUP_FILE dup

sed -i "1iSnapRAID Dup started at $(date)" $SNAPRAID_DUP_FILE
sed -i ';s/dup://g;s/: dup//g' $SNAPRAID_DUP_FILE
echo "SnapRAID Dup finished at $(date)" >> $SNAPRAID_DUP_FILE

echo "SnapRAID dup file created in"
echo "$SNAPRAID_DUP_FILE"
echo

exit 0
